### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by macmanes** [StepanAbstro/TransPrise#2]
Hello, 

I'm quite interested in using this software. It would be really helpful to have some more details about how to use it. Some example commands for prediction, for instance, would be great. 

Thanks, Matt

**Comment by StepanAbstro** [comment]
Hello, Matt.

You need to clone repository, create python environment with requirements.txt first. Next, workflow.py file is example of usage models on your own data. Sorry, for late response.

I think that here will be version 2 of transprise with userfriendly code and documentation.
